<?php

/**
 * BaseItemTyp
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * 
 * @method integer getId()   Returns the current record's "id" value
 * @method string  getName() Returns the current record's "name" value
 * @method ItemTyp setId()   Sets the current record's "id" value
 * @method ItemTyp setName() Sets the current record's "name" value
 * 
 * @package    workbook
 * @subpackage model
 * @author     Florian Engler
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseItemTyp extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('itemtyp');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             ));
        $this->hasColumn('name', 'string', 64, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 64,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}