<?php

/**
 * BaseFileJob
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $file_id
 * @property integer $job_id
 * 
 * @method integer getFileId()  Returns the current record's "file_id" value
 * @method integer getJobId()   Returns the current record's "job_id" value
 * @method FileJob setFileId()  Sets the current record's "file_id" value
 * @method FileJob setJobId()   Sets the current record's "job_id" value
 * 
 * @package    workbook
 * @subpackage model
 * @author     Florian Engler
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFileJob extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('file_job');
        $this->hasColumn('file_id', 'integer', 8, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 8,
             ));
        $this->hasColumn('job_id', 'integer', 8, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}