<?php

/**
 * BaseJobState
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property Doctrine_Collection $Jobs
 * 
 * @method integer             getId()   Returns the current record's "id" value
 * @method string              getName() Returns the current record's "name" value
 * @method Doctrine_Collection getJobs() Returns the current record's "Jobs" collection
 * @method JobState            setId()   Sets the current record's "id" value
 * @method JobState            setName() Sets the current record's "name" value
 * @method JobState            setJobs() Sets the current record's "Jobs" collection
 * 
 * @package    workbook
 * @subpackage model
 * @author     Florian Engler
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseJobState extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('job_state');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 64, array(
             'type' => 'string',
             'length' => 64,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Job as Jobs', array(
             'local' => 'id',
             'foreign' => 'job_state_id'));
    }
}