<?php

/**
 * BaseFile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $file
 * @property Doctrine_Collection $Jobs
 * 
 * @method integer             getId()   Returns the current record's "id" value
 * @method string              getName() Returns the current record's "name" value
 * @method string              getFile() Returns the current record's "file" value
 * @method Doctrine_Collection getJobs() Returns the current record's "Jobs" collection
 * @method File                setId()   Sets the current record's "id" value
 * @method File                setName() Sets the current record's "name" value
 * @method File                setFile() Sets the current record's "file" value
 * @method File                setJobs() Sets the current record's "Jobs" collection
 * 
 * @package    workbook
 * @subpackage model
 * @author     Florian Engler
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFile extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('file');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => 8,
             ));
        $this->hasColumn('name', 'string', 64, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 64,
             ));
        $this->hasColumn('file', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Job as Jobs', array(
             'refClass' => 'FileJob',
             'local' => 'file_id',
             'foreign' => 'job_id'));
    }
}