<?php

/**
 * BaseItemEntry
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $amount
 * @property integer $item_id
 * @property integer $job_id
 * @property Job $Job
 * @property Item $Item
 * 
 * @method integer   getId()      Returns the current record's "id" value
 * @method integer   getAmount()  Returns the current record's "amount" value
 * @method integer   getItemId()  Returns the current record's "item_id" value
 * @method integer   getJobId()   Returns the current record's "job_id" value
 * @method Job       getJob()     Returns the current record's "Job" value
 * @method Item      getItem()    Returns the current record's "Item" value
 * @method ItemEntry setId()      Sets the current record's "id" value
 * @method ItemEntry setAmount()  Sets the current record's "amount" value
 * @method ItemEntry setItemId()  Sets the current record's "item_id" value
 * @method ItemEntry setJobId()   Sets the current record's "job_id" value
 * @method ItemEntry setJob()     Sets the current record's "Job" value
 * @method ItemEntry setItem()    Sets the current record's "Item" value
 * 
 * @package    workbook
 * @subpackage model
 * @author     Florian Engler
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseItemEntry extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('itementry');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             ));
        $this->hasColumn('amount', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('item_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('job_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Job', array(
             'local' => 'job_id',
             'foreign' => 'id'));

        $this->hasOne('Item', array(
             'local' => 'item_id',
             'foreign' => 'id'));
    }
}