<?php

/**
 * BaseJobInvoice
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $job_id
 * @property integer $invoice_id
 * 
 * @method integer    getJobId()      Returns the current record's "job_id" value
 * @method integer    getInvoiceId()  Returns the current record's "invoice_id" value
 * @method JobInvoice setJobId()      Sets the current record's "job_id" value
 * @method JobInvoice setInvoiceId()  Sets the current record's "invoice_id" value
 * 
 * @package    workbook
 * @subpackage model
 * @author     Florian Engler
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseJobInvoice extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('job_invoice');
        $this->hasColumn('job_id', 'integer', 8, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 8,
             ));
        $this->hasColumn('invoice_id', 'integer', 8, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}