<?php

/**
 * BaseInvoice
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $number
 * @property Doctrine_Collection $Jobs
 * 
 * @method integer             getId()     Returns the current record's "id" value
 * @method integer             getNumber() Returns the current record's "number" value
 * @method Doctrine_Collection getJobs()   Returns the current record's "Jobs" collection
 * @method Invoice             setId()     Sets the current record's "id" value
 * @method Invoice             setNumber() Sets the current record's "number" value
 * @method Invoice             setJobs()   Sets the current record's "Jobs" collection
 * 
 * @package    workbook
 * @subpackage model
 * @author     Florian Engler
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseInvoice extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('invoice');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('number', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Job as Jobs', array(
             'refClass' => 'JobInvoice',
             'local' => 'invoice_id',
             'foreign' => 'job_id',
             'cascade' => array(
             0 => 'delete',
             )));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}