<?php

/**
 * BaseMessage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $parent
 * @property integer $sender
 * @property integer $reciver
 * @property integer $job_id
 * @property clob $body
 * @property sfGuardUser $User
 * @property Job $Job
 * 
 * @method integer     getId()      Returns the current record's "id" value
 * @method integer     getParent()  Returns the current record's "parent" value
 * @method integer     getSender()  Returns the current record's "sender" value
 * @method integer     getReciver() Returns the current record's "reciver" value
 * @method integer     getJobId()   Returns the current record's "job_id" value
 * @method clob        getBody()    Returns the current record's "body" value
 * @method sfGuardUser getUser()    Returns the current record's "User" value
 * @method Job         getJob()     Returns the current record's "Job" value
 * @method Message     setId()      Sets the current record's "id" value
 * @method Message     setParent()  Sets the current record's "parent" value
 * @method Message     setSender()  Sets the current record's "sender" value
 * @method Message     setReciver() Sets the current record's "reciver" value
 * @method Message     setJobId()   Sets the current record's "job_id" value
 * @method Message     setBody()    Sets the current record's "body" value
 * @method Message     setUser()    Sets the current record's "User" value
 * @method Message     setJob()     Sets the current record's "Job" value
 * 
 * @package    workbook
 * @subpackage model
 * @author     Florian Engler
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMessage extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('message');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             ));
        $this->hasColumn('parent', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('sender', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('reciver', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('job_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('body', 'clob', null, array(
             'type' => 'clob',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'sender',
             'foreign' => 'id'));

        $this->hasOne('Job', array(
             'local' => 'job_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}