<?php

/**
 * BaseTaskChangelog
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $user_id
 * @property string $action
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property integer $task_id
 * @property Task $Task
 * @property sfGuardUser $User
 * 
 * @method integer       getId()         Returns the current record's "id" value
 * @method integer       getUserId()     Returns the current record's "user_id" value
 * @method string        getAction()     Returns the current record's "action" value
 * @method timestamp     getCreatedAt()  Returns the current record's "created_at" value
 * @method timestamp     getUpdatedAt()  Returns the current record's "updated_at" value
 * @method integer       getTaskId()     Returns the current record's "task_id" value
 * @method Task          getTask()       Returns the current record's "Task" value
 * @method sfGuardUser   getUser()       Returns the current record's "User" value
 * @method TaskChangelog setId()         Sets the current record's "id" value
 * @method TaskChangelog setUserId()     Sets the current record's "user_id" value
 * @method TaskChangelog setAction()     Sets the current record's "action" value
 * @method TaskChangelog setCreatedAt()  Sets the current record's "created_at" value
 * @method TaskChangelog setUpdatedAt()  Sets the current record's "updated_at" value
 * @method TaskChangelog setTaskId()     Sets the current record's "task_id" value
 * @method TaskChangelog setTask()       Sets the current record's "Task" value
 * @method TaskChangelog setUser()       Sets the current record's "User" value
 * 
 * @package    workbook
 * @subpackage model
 * @author     Florian Engler
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTaskChangelog extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('taskchangelog');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('action', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('created_at', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('updated_at', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('task_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Task', array(
             'local' => 'task_id',
             'foreign' => 'id'));

        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}