<?php

/**
 * BaseTaskPosition
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $amount
 * @property integer $item_id
 * @property Item $Item
 * 
 * @method integer      getId()      Returns the current record's "id" value
 * @method integer      getAmount()  Returns the current record's "amount" value
 * @method integer      getItemId()  Returns the current record's "item_id" value
 * @method Item         getItem()    Returns the current record's "Item" value
 * @method TaskPosition setId()      Sets the current record's "id" value
 * @method TaskPosition setAmount()  Sets the current record's "amount" value
 * @method TaskPosition setItemId()  Sets the current record's "item_id" value
 * @method TaskPosition setItem()    Sets the current record's "Item" value
 * 
 * @package    workbook
 * @subpackage model
 * @author     Florian Engler
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTaskPosition extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('taskposition');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             ));
        $this->hasColumn('amount', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('item_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Item', array(
             'local' => 'item_id',
             'foreign' => 'id'));
    }
}