<?php

/**
 * BaseCalendar
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property timestamp $beginn
 * @property integer $duration
 * @property integer $job_id
 * @property integer $type_id
 * @property Job $Job
 * @property CalendarType $CalendarType
 * @property Doctrine_Collection $Users
 * 
 * @method integer             getId()           Returns the current record's "id" value
 * @method timestamp           getBeginn()       Returns the current record's "beginn" value
 * @method integer             getDuration()     Returns the current record's "duration" value
 * @method integer             getJobId()        Returns the current record's "job_id" value
 * @method integer             getTypeId()       Returns the current record's "type_id" value
 * @method Job                 getJob()          Returns the current record's "Job" value
 * @method CalendarType        getCalendarType() Returns the current record's "CalendarType" value
 * @method Doctrine_Collection getUsers()        Returns the current record's "Users" collection
 * @method Calendar            setId()           Sets the current record's "id" value
 * @method Calendar            setBeginn()       Sets the current record's "beginn" value
 * @method Calendar            setDuration()     Sets the current record's "duration" value
 * @method Calendar            setJobId()        Sets the current record's "job_id" value
 * @method Calendar            setTypeId()       Sets the current record's "type_id" value
 * @method Calendar            setJob()          Sets the current record's "Job" value
 * @method Calendar            setCalendarType() Sets the current record's "CalendarType" value
 * @method Calendar            setUsers()        Sets the current record's "Users" collection
 * 
 * @package    workbook
 * @subpackage model
 * @author     Florian Engler
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCalendar extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('Calendar');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             ));
        $this->hasColumn('beginn', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
        $this->hasColumn('duration', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('job_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('type_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Job', array(
             'local' => 'job_id',
             'foreign' => 'id',
             'cascade' => array(
             0 => 'delete',
             )));

        $this->hasOne('CalendarType', array(
             'local' => 'type_id',
             'foreign' => 'id'));

        $this->hasMany('sfGuardUser as Users', array(
             'refClass' => 'CalendarUser',
             'local' => 'calendar_id',
             'foreign' => 'user_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}