<?php

/**
 * BaseCalendarType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property Doctrine_Collection $Calendar
 * 
 * @method integer             getId()       Returns the current record's "id" value
 * @method string              getName()     Returns the current record's "name" value
 * @method Doctrine_Collection getCalendar() Returns the current record's "Calendar" collection
 * @method CalendarType        setId()       Sets the current record's "id" value
 * @method CalendarType        setName()     Sets the current record's "name" value
 * @method CalendarType        setCalendar() Sets the current record's "Calendar" collection
 * 
 * @package    workbook
 * @subpackage model
 * @author     Florian Engler
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCalendarType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('CalendarType');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             ));
        $this->hasColumn('name', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Calendar', array(
             'local' => 'id',
             'foreign' => 'type_id'));
    }
}