# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values

all:
  sf_guard_plugin:
    routes_register: false
    success_signin_url:      job/index # the plugin use the referer as default
    success_signout_url:     sfGuardAuth/signin         # the plugin use the referer as default