<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/07/18 18:51:14
sfConfig::add(array(
  'app_sf_guard_plugin_routes_register' => false,
  'app_sf_guard_plugin_success_signin_url' => 'calendar/day',
  'app_sf_guard_plugin_success_signout_url' => 'sfGuardAuth/signin',
));
