<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/07/09 13:21:39
sfConfig::add(array(
  'app_sf_guard_plugin_routes_register' => false,
  'app_sf_guard_plugin_success_signin_url' => 'calendar/index',
  'app_sf_guard_plugin_success_signout_url' => 'sfGuardAuth/signin',
));
