generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Task
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          task
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:   
        ID: { label: ID }
        End: { label: Ende }
        Start: { label: Start }
        Store: { label: Adresse }
        Job: { label: Auftrag }
      list:     
        title: Arbeitseinträge
        display: [id,job,Start,End]
        object_actions:
          _edit: ~
          _delete: ~
      filter:
        display: [users_list,start,end,scheduled,task_type_id]
      form:    ~
      edit:    ~
      new:     ~
