generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Invoice
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          invoice
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
              number: { label: Rechnungsnummer }
              created_at: { label: Erstellt am }

      list:
        display: [number,created_at]
        object_actions:
                  _delete: ~
      filter:
        display: [number,created_at,updated_at]
      form:    ~
      edit:    ~
      new:     ~
