<?php

/**
 * CalendarTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CalendarTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CalendarTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CalendarType');
    }
}