<?php

/**
 * CalendarUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CalendarUserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CalendarUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CalendarUser');
    }
}