<?php

/**
 * Customer
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    workbook
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Customer extends BaseCustomer
{
	public function __toString() 
	{
		return  str_pad($this->getNumber(), 4, "0", STR_PAD_LEFT).' '.$this->getCompany();
	}
	
	public function getNbStores() 
	{
		
		
		return link_to($this->getStores()->count(), 'store/list'); 
		
	}
	static public function retrieveForSelect($q, $limit )
	  {

		$query = Doctrine_Core::getTable('Customer')->createQuery('c');
		if(is_numeric($q)) $query->where(" c.number LIKE '$q%'");
		else if(strlen($q) > 1) $query->where("c.company LIKE '%$q%' ");
	

	    $stores = array();
	    foreach ($query->execute() as $store)
	    {
	      $stores[$store->getId()] = (string) $store;
	    }

	    return $stores;
	  }
	
}
