<?php

/**
 * Customer
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    workbook
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Customer extends BaseCustomer
{
	public function __toString() 
	{
		return $this->getNumber().' '.$this->getCompany();
	}
	
	public function getNbStores() 
	{
		
		
		return link_to($this->getStores()->count(), 'store/list'); 
		
	}
	
}
