<?php

/**
 * EntryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EntryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EntryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Entry');
    }

	public function getEntypByJob($Job){
		
		$output = array();
		
		$tasks = $this->jobs = Doctrine_Query::create()
				->select('*')
				->from('Task t')
				->where('t.job_id = '.$Job)
				->execute();
      $customCode = 1;
		
		foreach ($tasks as $task) {
			

			foreach ($task->getEntry() as $entry) {
			$mc = $entry->getItem()->getCode();
      if(empty($mc)) {
          $mc = '#CC'.$customCode;
          $customCode++;
      }
        echo $mc.'<br>';
			if(!isset($output[$mc])){
				$output[$mc] = array();
				$output[$mc]['amount'] = 0;
			}
	
			$output[$mc]['amount'] += $entry->getAmount();
			$output[$mc]['item'] =	$entry->getItem();
			$output[$mc]['description'] =	$entry->getDescription();
			}
			
		}
		
		return $output;
		
	}
}