<?php

/**
 * FileJobTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FileJobTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FileJobTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FileJob');
    }
}