<?php

/**
 * ItemMasterTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ItemMasterTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ItemMasterTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ItemMaster');
    }
}