<?php

/**
 * ItemTypTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ItemTypTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ItemTypTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ItemTyp');
    }
}