<?php

/**
 * ItemEntryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ItemEntryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ItemEntryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ItemEntry');
    }
}