<?php

/**
 * Item
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    workbook
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Item extends BaseItem
{
	public function __toString()
	{
		return  $this->getCode().' '.$this->getDescription();
	}
	static public function retrieveForSelect($q, $limit)
	  {
	   // $criteria = new Criteria();
	   // $criteria->add(store::Street, '%'.$q.'%', Criteria::LIKE);
	   // $criteria->addAscendingOrderByColumn(store::Street);
	   // $criteria->setLimit($limit);
		$query = Doctrine_Core::getTable('Item')->createQuery('s');
		if (strlen($q) > 2) 
			{
			$query->where(" s.code LIKE '$q%' or s.description LIKE '%$q%' ");
			}
		else	
			{
			$query->where(" s.code LIKE '$q%' ");
			}
	
	

	    $items = array();
	    foreach ($query->execute() as $item)
	    {   
	     $items[$item->getId()] = (string) $item ;
		  
	    }
	return $items;
	}
	
}
