<?php

/**
 * Job
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    workbook
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Job extends BaseJob
{
	public function __toString()
	{
		return  substr($this->getStore()->getCustomer()->getCompany(),0,20).' - '.$this->getStore();
	}
	
	public function hasSheduledTasks()
	{
		$tasks = Doctrine_Query::create()
				->select('t.*')
				->from('task t')
				->where('job_id ='.$this->getId().' 
						AND scheduled IS TRUE ')
				->execute();
		if ($tasks->count() != 0) {
			return true;
		}
		else return false;
	}
	
	
}
