<?php

/**
 * JobChangelogTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class JobChangelogTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object JobChangelogTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('JobChangelog');
    }

	public static function getLastChange($id)
    {
        
	$changes = Doctrine_Query::create()
						->select('*')
						->from('JobChangelog j')
						->where('j.job_id = '.$id)
						->orderby('j.updated_at')
						->execute();
     return  $changes[0];
	}
	
}