<?php

/**
 * JobChangelogTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class JobChangelogTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object JobChangelogTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('JobChangelog');
    }
}