<?php

/**
 * JobStateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class JobStateTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object JobStateTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('JobState');
    }
}