<?php

/**
 * JobUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class JobUserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object JobUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('JobUser');
    }

    public static function deleteJobUser($jobid){

        $JUs = Doctrine_Query::create()
            ->select('*')
            ->from('JobUser ju')
            ->where('ju.job_id = '.$jobid)
            ->execute();
        foreach($JUs as $ju){
            $ju->delete();
        }

    }
}