<?php

/**
 * Option
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    workbook
 * @subpackage model
 * @author     Florian Engler
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Option extends BaseOption
{
	public function __toString()
	{
		return  $this->getValue();
	}
	
	
	
}
