<?php

/**
 * OptionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OptionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OptionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Option');
    }
	
	public function getOptionByName($option)
	  {
	    $value = Doctrine_Query::create()
						->select('*')
						->from('Option o')
						->where("o.name = '$option'")
						->fetchOne();
	    $return = $value->getValue();
		settype($return,$value->getType());
	  	return $return;
	}



}