<?php

/**
 * Store
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    workbook
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Store extends BaseStore
{
	public function __toString()
	{
		return  $this->getNumber()
				.' | '.str_pad($this->getPostcode(),5)
				.' '.$this->getCity()
				.' '.$this->getStreet();
	}
	

	
	static public function retrieveForSelect($q, $limit, $customer)
	  {
	   // $criteria = new Criteria();
	   // $criteria->add(store::Street, '%'.$q.'%', Criteria::LIKE);
	   // $criteria->addAscendingOrderByColumn(store::Street);
	   // $criteria->setLimit($limit);
		$query = Doctrine_Core::getTable('Store')->createQuery('s')
				->innerJoin('s.Customer c WITH c.number = '.$customer );
		
		if(is_numeric($q)) $query->where(" s.number LIKE '$q%'");
		else if(strlen($q) > 1) $query->where("s.street like '$q%' ");
	

	    $stores = array();
	    foreach ($query->execute() as $store)
	    {
		   
	      $stores[$store->getId()] = (string) $store;
	/*	'<div style="display:inline-block; width:30px;" >'.$store->getCustomer()->getNumber().'</div>'.
											'<div style="display:inline-block;width:120px;">'.substr($store->getCustomer()->getCompany(),0,15).'</div>'.
											'<div style="display:inline-block;width:30px;" >'.$store->getNumber().'</div>'.
											'|<div style="display:inline-block;width:40px;">'.$store->getPostcode().'</div>'.
											'<div style="display:inline-block;width:200px;">'.$store->getStreet().'</div>';
		*/
	    }

	    return $stores;
	  }
	
}
