<?php

/**
 * TaskPositionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TaskPositionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TaskPositionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TaskPosition');
    }
}