<?php

/**
 * TaskChangelogTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TaskChangelogTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TaskChangelogTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TaskChangelog');
    }
}