<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/07/07 16:37:59
sfConfig::add(array(
  'mod_sfguardpermission_enabled' => true,
  'mod_sfguardpermission_view_class' => 'sfPHP',
));
