<?php

/**
 * sfGuardUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardUserTable extends PluginsfGuardUserTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object sfGuardUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfGuardUser');
    }


    public function getActive(){
        return Doctrine_Query::create()
            ->select('*')
            ->from('sfGuardUser u')
            //->where('u.is_active = 1')
            ->where('u.is_user = 1')
            ->execute();
    }
}