generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Job
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          job
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
        ID: { label: ID }
        End: { label: Ende }
        Start: { label: Start }
        Store: { label: Adresse }
        JobState: { label: Status }
      list:
        title: Aufträge
        display: [ID,Store,Start,End,Job_State]
        object_actions:
          _edit: ~
          _delete: ~
      filter:
        display: [job_state_id,store_id,start,end] 
      form:    ~
      edit:
        title: Bearbeiten von Auftrag Nummer %%id%%<br> in %%store%%  
      new:
        title: Neuer Auftrag

