generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Job
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          job
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        id: { label: Auftragsnummer }  
        start: { label: Beginn, help: Beginn des Auftrags }
        end: { label: Ende, help: Ende des Auftrags}
        store: { label: Adresse, help: Die Adresse des Kunden oder des Auftrags}
      list:    
        title: Auftragsverwaltung
        display: [id, start, end, store]
        object_actions:
             _edit: ~
             _delete: ~
      filter:  
        display: [start, end,store_id]
      form:    ~
      edit:
        title: Bearbeiten von Auftrag Nummer %%id%%<br> in %%store%%  
      new:
        title: Neuer Auftrag

