<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/06/04 14:40:30
sfConfig::add(array(
  'mod_sfguardpermission_enabled' => true,
  'mod_sfguardpermission_view_class' => 'sfPHP',
));
