<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/07/16 15:03:47

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=workbook',
  'username' => 'root',
  'password' => 'root',
  'name' => 'doctrine',
)),);
